### ISSUE TITLE
Pagina di spiegazione

### ISSUE THREAD

**Issue by Mte90** [iojs/iojs-it#10]
Per iniziare è bene rendersi conto del volume di file da tradurre.
é il caso di caricare quindi gli altri oltre ad index.html

**Comment by parroit** [comment]
Ciao @Mte90. Allo stato attuale abbiamo tradotto tutti i file del sito, li puoi vedere nel branch [website-pr di questo repo](https://github.com/iojs/iojs-it/tree/website-pr/content/it). 

Dovremmo preparare un elenco dei post da tradurre da medium.com

**Comment by Mte90** [comment]
Allora conviene fare una pagina sul wiki per spiegare dove sono i file da tradurre e le cose da fare.

**Comment by parroit** [comment]
Faccio una bozza... poi la miglioriamo.
