### ISSUE TITLE
Regole stilistiche

### ISSUE THREAD

**Issue by Mte90** [iojs/iojs-it#11]
Ogni progetto collaborativo ha bisogno di regole specialmente in ambito di localizzazione.
Suggerisco il mio articolo http://www.mte90.net/2014/10/come-traduttore-per-progetti-open-source/ che contiene i riferimenti alle linee guida di Mozilla Italia e di altri progetti.

**Comment by mcollina** [comment]
Per me :+1:, lo mettiamo nel readme?

**Comment by parroit** [comment]
:+1  per metterlo nel README e mi leggo subito il tuo articolo @Mte90

**Comment by Mte90** [comment]
L'articolo è più per i newbie generici ma contiene qualche link che può essere utile.
Ho fatto qualche piccola revisione ma erano solo delle forme un tantino arzigogolate per il resto avete già fatto un ottimo lavoro :-)

**Comment by parroit** [comment]
Grazie... ho fatto una bozza della pagina wiki, guarda se ti sembra chiara

**Comment by parroit** [comment]
Cos'è `Transifex`? Ho visto che lo stanno usando anche il gruupo spagnolo...

**Comment by Mte90** [comment]
Il wiki è chiaro :-)
Transifex.com è un servizio online gratuito per i progetti open per la traduzione semplificata dei software tramite una piattaforma collaborativa.

**Comment by parroit** [comment]
E l'articolo molto interessante...
Quindi se ho capito bene , nelle regole di stile andiamo a spiegare ad esempio come traduciamo "Issues" 
o "Pull Request"  ecc. (Cose che in effetti abbiamo discusso)

**Comment by parroit** [comment]
Forse possiamo trovare qualcosa di già fatto e seguirlo? @Mte90 hai qualche info su altri progetti OS?

**Comment by Mte90** [comment]
Si esatto fare un piccolo vocabolario dei termini per essere sicuri delle loro traduzioni.
Nell'articolo ci sono degli elenchi ma altri utili alla nostra causa non mi vengono in mente per il momento.

**Comment by parroit** [comment]
Secondo me potremmo prendere come base il [regolamento di Mozilla](http://www.mozillaitalia.org/home/regole-generali-di-traduzione/) linkandolo, e poi nella wiki integriamo con quello che manca. Nel README metterei un link alla pagina wiki su come collaborare

**Comment by parroit** [comment]
Fatto

**Comment by hex7c0** [comment]
:+1:
