### ISSUE TITLE
Proposal: rename the nodejs/iojs-it WG to nodejs/nodejs-it

### ISSUE THREAD

**Issue by srl295** [iojs/iojs-it#17]
Dear members of the io.js Italian WG `iojs-it`

It is proposed to rename this repo to:

   [nodejs/nodejs-it](https://github.com/nodejs/nodejs-it/)

As part of the io.js and node.js convergence, node.js releases are now based on the codebase and user base of the converged node.js and io.js communities. A number of the resources and repositories have already been renamed.
In the absence of objections or other discussion, this rename will occur on or after [Oct 28, 2015](http://time.is/1200AM_28_Oct_2015_in_GMT?iojs-rename)

However, active language working groups should take ownership of this issue and discuss/dispose of it according to their own processes.

For more information or to discuss the overall issue, please see and comment on https://github.com/nodejs/node/issues/2525

This statement was authorized by the Node.js TSC

Cc: @nodejs/iojs-it

**Comment by mcollina** [comment]
:+1: go ahead and rename.

**Comment by piccoloaiutante** [comment]
yep go on :+1:

**Comment by parro-it** [comment]
:+1:  great

**Comment by hex7c0** [comment]
:+1: @srl295

**Comment by srl295** [comment]
Done.
