### ISSUE TITLE
Organizzazione iojs-it

### ISSUE THREAD

**Issue by parroit** [iojs/iojs-it#6]
Se facessimo una organizzazione iojs-it su GH, potremmo fare un fork del repo website, fare i nostri push tutti lì e poi fare PR singole quando i testi ci sembrano a posto. Cosa ne pensate

**Comment by mcollina** [comment]
Possiamo fare PR singole anche qui, non vedo perché fare una nuova organizzazione.

**Comment by parroit** [comment]
uhm, non sono proprio esperto di workflow su GH, mi spieghi in chat come fare?

**Comment by mcollina** [comment]
Fai un clone di questo repo sul tuo pc, `git branch <nomebranch>`, `git push`, e poi apri il sito e c'è un bottone 'compare..' in verde su sfondo giallo con il nome della branch.

**Comment by parroit** [comment]
ok, se ho capito mi faccio un branch locale, su questo branch faccio pull da https://github.com/iojs/website, poi faccio push del branch qui.
A quel punto facciamo tutti push delle modifiche su questo branch, e poi facciamo la PR di questo branch. Ti torna?

**Comment by mcollina** [comment]
Proviamo! :)

Il giorno Wed Feb 18 2015 at 19:20:51 Andrea Parodi <
notifications@github.com> ha scritto:

**Comment by parroit** [comment]
ok provo...

**Comment by parroit** [comment]
Mi sa che non va...
Ho usato questi comandi:

``` sh
git clone https://github.com/iojs/iojs-it.git
git branch website-pr
git checkout website-pr
git rm -rf .
git push origin website-pr
git remote add upstream https://github.com/iojs/website.git
git pull upstream master
git push origin website-pr
```

come puoi vedere ora nel branch website-pr c'è tutto il contenuto di https://github.com/iojs/website, però se provi a fare un PR, ti propone come destinazione solo gli altri branch di questo repo, probabilmente GH non riesce a riconoscere il collegamento fra i due repo che ci interessano

**Comment by parroit** [comment]
Francesco ha già fatto una PR della index.html, ma partendo dal repo forkato sul suo account... volendo si può fare anche così: ognuno si fa una fork sul suo account, fa le modifiche che gli competono, e poi per pubblicare una sola PR con tutti i file, chi se ne occupa fa il merge dai repo forkati sui vari account sul suo, e poi fa PR da lì
Non so se ho spiegato bene l'idea...

**Comment by mcollina** [comment]
Ci guardo appena ho tempo, così non va bene. Guarda come fanno gli altri, al massimo chiedi a loro.

**Comment by parroit** [comment]
Aspetta mi è venuta un'idea + semplice: facciamo tutti push sul branch che ho creato, poi per creare la PR facciamo fork del repo `website` su un nostro account, mergiamo questo branch e PR.
Così è molto più semplice... provo

**Comment by parroit** [comment]
Mi sembra che così funzioni... ho creato qui un branch website-pr, dove ho riportato i file che abbiamo già tradotto Francesco ed io **per favore fate il push di altre modifiche su questo branch**

Poi ho fatto un fork del repo iojs/website, in lopcale ho fatto il merge dei due, il push sul mio fork, e dal mio account riesco a fare una PR dei file modificati (naturalmente non l'ho fatta veramente)

Mi sembra abbastanza semplice da gestire, domani magari scrivo un po di istruzioni in wiki

**Comment by parroit** [comment]
Ho fatto qualche ricerca sugli altri gruppi al riguardo, per sapere come si stanno organizzando. Ne stanno discutendo [gli spagnoli](https://github.com/iojs/iojs-es/issues/38)

**Comment by parroit** [comment]
Abbiamo discusso il metodo con @stringparser del gruppo spagnolo, che mi ha dato qualche buona dritta sull'uso di git. Riepilogo il metodo che propongo di usare:

##Creazione branch di lavoro

Questo branch conterrà una copia del [repo website](https://github.com/iojs/website) di iojs.
Su questo branch diovremmo fare tutti il push delle nostre modifiche, e non sarà necessario tenere il content delle altre lingue aggiornato con il repo originale.
Ho già creato il branch website-pr, che contiene una copia del contenuto aggiornato all'altro ieri.

Per crearlo, da locale ho usato i seguenti comandi:

``` sh
git clone https://github.com/iojs/iojs-it.git
git branch website-pr
git checkout website-pr
git rm -rf .
git remote add upstream https://github.com/iojs/website.git
git pull upstream master
git push origin website-pr
```

E poi ho aggiornato i file di content/it e fatto un altro push.

##Preparazione di una PR

Quando siamo pronti per fare una PR, dobbiamo su uno dei nostri account fare il fork del repo website,
pull in locale, e poi copiarci sopra i file content/it che peschiamo dal nostro branch, con il comando
`git checkout content/it`, eseguito con cwd nel repo del nostro branch

``` sh
git remote add translation https://github.com/iojs/iojs-it
git checkout translation/website-pr content/it
git commit -m ""
```

A quel punto possiamo fare la PR. Il metodo mi sembra semplice, se va bene a tutti provo ad usarlo.

**Comment by mcollina** [comment]
:+1:

**Comment by hex7c0** [comment]
tenere il brach `website-pr` mi pare inutile
era stato fatto il branch `website` apposta

quando si è in procinto di caricare una traduzione al sito originale, si fa il merge del branch `website` nel `master`
e push su `iojs/website`

**Comment by parroit** [comment]
Non vorrei imporre niente, basta trovare un modo condiviso...
solo non ho capito perchè fai il merge da website a master, mi sembra inutile...
Comunque possiamo benissimo tenere solo il content/it su website e copiarlo sul fork locale di chi preparerà la PR.
Mi sembra però più pratico tenere sul branch website tutto il materiale che c'è sul repo iojs/website, in questo modo i nuovi arrivati possono fare pull di quello e cominciare a contribuire.

**Comment by hex7c0** [comment]
merge con `master` è utile per confermare le modifiche, mentre `X` branch per lavorare su una traduzione finché non è "stable"

serve solo `content/it` per evitare confusione
infatti avevo erroneamente scritto `index.html` perchè l'ho preso dalla dir sbagliata

**Comment by parroit** [comment]
Ok, riepilogo i due metodi e poi direi di mettere ai voti (correggimi se non ho capito bene il tuo workflow)

Metodo 1 (branch website contiene solo content/it)

1) si fa il clone di `https://github.com/iojs/website master` in locale
2) si fa il clone di `https://github.com/iojs/iojs-it website` in locale
3) si copiano i file da `content/it` di `https://github.com/iojs/iojs-it website` su `https://github.com/iojs/website master`
4) si lavora in locale su `https://github.com/iojs/website master`
5) si copiano i file da `content/it` di `https://github.com/iojs/website master` su `https://github.com/iojs/iojs-it website`
6) si fa commit di `https://github.com/iojs/iojs-it website`
7) quando ci sembra che i file vadano bene, facciamo una PR da website a master e valutiamo
8) se tutto ok, fork di `https://github.com/iojs/website master` su un nostro account e aggiornamento in locale dei file di content/it da `https://github.com/iojs/iojs-it website`
9) PR

Metodo 2 (branch website contiene tutto il contenuto di iojs/website)

1) si fa il clone in locale di `https://github.com/iojs/iojs-it website`
2) si lavora in locale sul clone `https://github.com/iojs/iojs-it website`
3) si fa commit di `https://github.com/iojs/iojs-it website`
4) quando ci sembra che i file vadano bene, fork di `https://github.com/iojs/website master` su un nostro account e aggiornamento in locale i file _solo_ di content/it da `https://github.com/iojs/iojs-it website`
5) PR

**Comment by parroit** [comment]
Abbiamo trovato una quadra con @hex7c0 .
- facciamo un branch per ogni tipo di contenuto (sito web, post su medium ecc.)
- questi branch conterranno solo il contenuto da tradurre (quindi non ad esempoio tutto il sito)
- facciamo i push su quei branch (se diventassimo tanti chi non sarà contributor farà PR lì)
- quando siamo pronti a pubblicare un branch, ne facciamo una PR su master, ne valutiamo la qualità e poi da master pubblichiamo in base al loro tipo (PR su iojs/website o pubblicazione su medium ecc.
  )

Le traduzioni del sito le faremo senza visualizzare il contenuto compilato su gulp. Valuteremo eventuali problemi di stile al momento della PR da website a master

fate :+1: o :-1: (e dite la vostra) e poi correggiamo il tiro, oppure scriviamo il workflow sul wiki

**Comment by parroit** [comment]
chiudo...
