### ISSUE TITLE
Problema versioni

### ISSUE THREAD

**Issue by parroit** [iojs/iojs-it#7]
Ci sono vari punti nelle pagine dove vengono citate versioni di node, iojs, npm ecc. che sono datate. Che fare?

1) Teniamo le versioni che ci sono in inglese
2) Utilizziamo le versioni attuali (ma poi che facciamo, le aggiornamo in futuro tutte le volte che cambiano?)

**Comment by mcollina** [comment]
Usiamo le versioni in inglese, forse è meglio.

**Comment by parroit** [comment]
Sono d'accordo...

**Comment by hex7c0** [comment]
concordo.
chiudo

**Comment by parroit** [comment]
https://github.com/iojs/website/issues/220
