### ISSUE TITLE
Problemi di stile

### ISSUE THREAD

**Issue by parroit** [iojs/iojs-it#8]
La pagina index ha evidenziato alcuni problemi di stile, che devono essere segnalati a parte.
Dovremmo 

1) raggruppare tutti i problemi di questo tipo che abbiamo trovato
2) identificare eventuali issues o PR già create dagli altri gruppi locali a riguardo, giusto per non creare dulicati
3) eventualmente vedere noi come risolvere e fare delle PR (es. il problema della index è che il .content ha un max-width di 640px, insufficiente per contenere tutte le etichette della sezione inferioe in italiano)

**Comment by hex7c0** [comment]
from https://github.com/iojs/website/blob/master/TRANSLATION.md
`Do not make language specific changes to layout or styling in a translation PR. If they are needed, make a separate styling/layout pr and chat with one of the website WG about the change. We want to make sure, for example, a Chinese layout change doesn't cascade failure to the German page.`

**Comment by parroit** [comment]
Ho abbreviato un po' le etichette nel file json, così sta tutto in il footer in riga... guardate se vi piace
