### ISSUE TITLE
modifica al titolo

### ISSUE THREAD

**Issue by parroit** [iojs/iojs-it#9]
Ho visto che altre comunità nella descrizione del repo hanno inserito una descrizione in lingua dello scopo del repo stesso, piuttosto che la descrizione tradotta del repo di iojs (che non mi sembra abbia molto senso).

Nel nostro caso diventerebbe 

"Localizzazione e traduzione di io.js in Italiano."

Cosa ne dite'

**Comment by mcollina** [comment]
:+1:, manda una PR.

**Comment by parroit** [comment]
Penso che lo possiamo fare direttamente

**Comment by parroit** [comment]
fatto!
